name: Daily BTC/USD ETL Pipeline
on:
  schedule:
    - cron: "0 4 * * *" # Runs daily at 4:00 AM UTC
  workflow_dispatch: # Allows manual triggering
jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Extract data
        run: python extract.py
      - name: Transform data
        run: python transform.py
      - name: Load data
        run: python load.py
      - name: Upload raw data artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-data
          path: raw_btc_usd.csv
          retention-days: 1
      - name: Commit chart to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Move chart to temporary location to avoid checkout conflict
          mkdir -p temp
          mv charts/btc_usd_chart.html temp/ || true
          if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
          fi
          # Restore chart to charts/
          mkdir -p charts
          mv temp/btc_usd_chart.html charts/ || true
          git add charts/btc_usd_chart.html
          git commit -m "Update BTC/USD chart for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/carlosmassa/btc-etl-pipeline.git gh-pages
