name: Daily BTC/USD ETL Pipeline
on:
  schedule:
    - cron: "0 4 * * *" # Runs daily at 4:00 AM UTC
  workflow_dispatch: # Allows manual triggering
jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Extract data
        run: python extract.py
      - name: Transform data
        run: python transform.py
      - name: Load data
        run: python load.py
      - name: Commit chart to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin gh-pages || git branch gh-pages
          git checkout gh-pages
          git add charts/*
          git commit -m "Update BTC/USD chart for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push origin gh-pages
