name: Daily BTC Prices (CoinMetrics)
on:
  schedule:
    - cron: "0 3 * * *"  # 3 AM UTC, before the 4 AM UTC main ETL
  workflow_dispatch:

jobs:
  coinmetrics_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CoinMetrics incremental ETL
        run: python scripts/update_btc_price_coinmetrics.py

      - name: Commit updated CSV
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/BTC_Prices.csv
          git commit -m "Auto-update BTC prices for $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
